//! **Filling a staged set** — the treeline, the skyline, the grass, the rain.
//!
//! # The gap this closes
//!
//! [`crate::staging`] builds the *arrangement*: a ground plane, a backdrop, a
//! light rig that agrees with itself, and a cast standing at plausible sizes.
//! What it has never built is anything to look at. After it ran, the largest
//! remaining task in the shot was drawing the background — and the fifteen
//! effect brushes that would paint it had been sitting in
//! [`buzz_scene::effect_brush`] the whole time, reachable only by hand.
//!
//! So this is the join: a setting, and the strokes an animator would have
//! dragged for it.
//!
//! # It lays strokes, it does not invent a brush
//!
//! Every piece of scenery here is **one effect-brush stroke** — the same call
//! the Brush tool makes, with the same budgets and the same determinism. What
//! lands on the layer is ordinary grouped artwork: selectable, movable,
//! deletable, and drawable-over. Nothing here is live and nothing re-runs.
//!
//! That matters more than it sounds. A background generated by some private
//! path would be a background the animator could not extend with the brush
//! that made it; going through the public brush means the treeline they get
//! and the treeline they paint next to it are the same kind of thing.
//!
//! # Depth, and why the strokes are not all on one layer
//!
//! Scenery goes on its own layers at its own depths, behind the cast and in
//! front of the sky. A treeline at the horizon and grass at the camera's feet
//! are different distances, and putting them on one layer would flatten the
//! parallax the depth system already gives for free.

use buzz_geom::{Conditioning, Point, StrokeSample};
use buzz_scene::{
    EffectKind, EffectStroke, LayerKind, Scene, effect_artwork,
};
use peniko::Color;

use crate::staging::Setting;

/// **What is in the shot besides the ground and the sky.**
///
/// A choice rather than something inferred from the setting, because the
/// setting says *when* and this says *where*: a night could be a forest or a
/// street, and the light rig is the same either way.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Scenery {
    /// Nothing. The bare set [`crate::staging::build`] has always made.
    #[default]
    Bare,
    /// A treeline along the horizon and grass in the foreground.
    Forest,
    /// A lit skyline along the horizon, and street lamps on the path.
    City,
    /// Open ground: grass near, and a thin line of trees far off.
    Meadow,
    /// A shore: water at the horizon, grass on the bank.
    Waterside,
}

impl Scenery {
    pub fn label(self) -> &'static str {
        match self {
            Self::Bare => "Bare",
            Self::Forest => "Forest",
            Self::City => "City",
            Self::Meadow => "Meadow",
            Self::Waterside => "Waterside",
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::Bare => "Ground and sky, and nothing between them",
            Self::Forest => "A treeline along the horizon, grass at the front",
            Self::City => "A lit skyline, and street lamps down the path",
            Self::Meadow => "Open ground: grass near, a thin line of trees far off",
            Self::Waterside => "A shore, with the bank in front of it",
        }
    }

    /// **Read a scenery out of a brief.**
    ///
    /// The same shape as the director's `clouds` and `water` triggers, and for
    /// the same reason: a writer who says *forest* has said what the shot looks
    /// like, and asking them to say it twice — once in the prose and once in a
    /// dialog — is the kind of thing that makes a tool feel like paperwork.
    ///
    /// Checked most specific first. A brief that says both *city* and *trees*
    /// is a city with trees in it, and the skyline is the thing that makes it
    /// read as one.
    pub fn from_prose(text: &str) -> Self {
        let lower = text.to_lowercase();
        let has = |words: &[&str]| words.iter().any(|w| lower.contains(w));

        if has(&[
            "city", "street", "town", "rooftop", "skyline", "alley", "downtown",
            "pavement", "sidewalk",
        ]) {
            Self::City
        } else if has(&["forest", "wood", "trees", "pine", "grove", "thicket"]) {
            Self::Forest
        } else if has(&[
            "river", "lake", "shore", "beach", "sea", "ocean", "canal", "stream",
        ]) {
            Self::Waterside
        } else if has(&["meadow", "field", "hill", "moor", "grass", "plain"]) {
            Self::Meadow
        } else {
            Self::Bare
        }
    }
}

/// What was laid down.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SceneryReport {
    /// The layers made, back to front.
    pub layers: Vec<buzz_scene::LayerId>,
    /// Objects added across all of them.
    pub pieces: usize,
}

/// **Lay the scenery for `what` into `scene`.**
///
/// `horizon_y` is where the ground meets the sky — [`crate::staging::build`]
/// knows it and this does not, and guessing it from the stage rectangle would
/// put a treeline through the middle of a low-horizon shot.
///
/// # Where the layers land
///
/// `backdrop` is the sky layer, when there is one. Everything **far** — a
/// treeline, a skyline — is moved to sit directly in front of it and therefore
/// behind the cast; everything **near** — grass, a bank — stays at the front,
/// where a foreground belongs.
///
/// Getting this wrong is not subtle. The first version added every layer at the
/// front and said in a comment that they went behind, and the figure it was
/// meant to illustrate came back with a forest painted over the actor.
pub fn lay(
    scene: &mut Scene,
    what: Scenery,
    horizon_y: f64,
    backdrop: Option<buzz_scene::LayerId>,
) -> SceneryReport {
    let mut out = SceneryReport::default();
    if what == Scenery::Bare {
        return out;
    }
    let stage = scene.stage().stage_rect();
    // Wider than the stage, for the same reason the backdrop is: a camera that
    // pans must not run off the end of the treeline.
    let x0 = stage.x0 - stage.width() * 0.5;
    let x1 = stage.x1 + stage.width() * 0.5;

    // (name, kind, y, size, colour, depth) — back to front.
    //
    // **The sizes were tuned against the render, not reasoned about.** A brush
    // size is the scale of everything the effect lays down, and the first set
    // of numbers here — picked by eye from the stage height — produced a
    // treeline that filled the frame and dwarfed the cast. The figure in the
    // guide is what showed it; these are what came back.
    // The last field is **far**: does this go behind the cast, or in front?
    let plan: Vec<(&str, EffectKind, f64, f64, Color, f64, bool)> = match what {
        Scenery::Bare => Vec::new(),
        Scenery::Forest => vec![
            (
                "Treeline",
                EffectKind::PineTrees,
                horizon_y,
                stage.height() * 0.11,
                Color::from_rgb8(0x1E, 0x2E, 0x24),
                0.7,
                true,
            ),
            (
                "Grass",
                stage_grass(),
                stage.y1 - stage.height() * 0.04,
                stage.height() * 0.045,
                Color::from_rgb8(0x2C, 0x44, 0x2E),
                -0.3,
                false,
            ),
        ],
        Scenery::City => vec![
            (
                "Skyline",
                EffectKind::Buildings,
                horizon_y,
                stage.height() * 0.15,
                Color::from_rgb8(0x18, 0x1C, 0x2A),
                0.8,
                true,
            ),
            (
                "Street Lamps",
                EffectKind::Lamps,
                horizon_y + stage.height() * 0.10,
                stage.height() * 0.09,
                Color::from_rgb8(0xFF, 0xD9, 0x9E),
                0.2,
                true,
            ),
        ],
        Scenery::Meadow => vec![
            (
                "Far Trees",
                EffectKind::LeafyTrees,
                horizon_y,
                stage.height() * 0.07,
                Color::from_rgb8(0x33, 0x46, 0x38),
                0.85,
                true,
            ),
            (
                "Grass",
                stage_grass(),
                stage.y1 - stage.height() * 0.06,
                stage.height() * 0.05,
                Color::from_rgb8(0x3A, 0x54, 0x36),
                -0.3,
                false,
            ),
        ],
        Scenery::Waterside => vec![
            (
                "Far Trees",
                EffectKind::LeafyTrees,
                horizon_y,
                stage.height() * 0.06,
                Color::from_rgb8(0x2A, 0x3C, 0x33),
                0.85,
                true,
            ),
            (
                "Bank",
                stage_grass(),
                stage.y1 - stage.height() * 0.05,
                stage.height() * 0.045,
                Color::from_rgb8(0x35, 0x4C, 0x33),
                -0.3,
                false,
            ),
        ],
    };

    for (name, kind, y, size, colour, depth, far) in plan {
        // **A straight stroke across the shot.** The effect brushes scatter
        // along their own spine, so a level line is not a level result — it is
        // a treeline of varying heights standing on level ground, which is what
        // a treeline is.
        let samples: Vec<StrokeSample> = (0..48)
            .map(|i| {
                let t = i as f64 / 47.0;
                StrokeSample::new(Point::new(x0 + (x1 - x0) * t, y), 1.0)
            })
            .collect();

        let pieces = effect_artwork(
            kind,
            &EffectStroke {
                samples: &samples,
                size,
                color: colour,
                // Nothing to smooth: the spine is a straight line already, and
                // conditioning it would only cost time.
                conditioning: Conditioning::smoothing(0.0),
            },
        );
        if pieces.is_empty() {
            continue;
        }

        // Behind everything already staged, and at its own depth so the
        // parallax the depth system gives comes for free.
        let layer = scene.add_stage_layer(name, LayerKind::Normal);
        scene.update_layer(layer, |l| l.depth = depth);

        let mut register = |canvas: &buzz_scene::Canvas, brush: &buzz_scene::SoftBrush| {
            let id = scene.next_image_id();
            let asset_name = scene.images().unique_name(name);
            scene.images_mut().insert(canvas.to_asset(id, asset_name, brush))
        };
        let shapes = buzz_scene::art::to_shapes(&pieces, &mut register);
        for shape in shapes {
            if scene.add_shape(layer, shape).is_some() {
                out.pieces += 1;
            }
        }
        // **Far scenery goes behind the cast.** Moved to sit directly in front
        // of the backdrop, which is where a horizon belongs; near scenery is
        // left at the front, which is where a foreground belongs.
        if far
            && let Some(sky) = backdrop
            && let Some(at) = scene.stage_layer_index(sky)
            && at > 0
        {
            // **One less than the sky's index**, because the move takes this
            // layer out of the front first and everything behind it shifts up
            // by one. Reordering to `at` lands it *behind* the sky, where
            // nobody can see it — which is what the first attempt did.
            scene.reorder_stage_layer(layer, at - 1);
        }
        out.layers.push(layer);
    }
    out
}

/// Grass, named apart so the two places that want it cannot disagree about
/// which effect grass is.
fn stage_grass() -> EffectKind {
    EffectKind::Grass
}

/// **What weather this setting brings**, if any.
///
/// A storm arrives with rain whether the writer mentioned it or not, for the
/// same reason it arrives with cloud: it is what a storm *is*, and a rule that
/// lived in each caller is a rule that gets out of step.
pub fn weather_for(setting: Setting) -> Option<EffectKind> {
    match setting {
        Setting::Storm => Some(EffectKind::Rain),
        _ => None,
    }
}

/// Lay `weather` across the whole frame, in front of the scenery and behind
/// nothing — rain falls between the camera and everything else.
pub fn lay_weather(scene: &mut Scene, kind: EffectKind) -> SceneryReport {
    let mut out = SceneryReport::default();
    let stage = scene.stage().stage_rect();
    let wide = stage.inflate(stage.width() * 0.5, stage.height() * 0.5);

    // Weather fills the frame rather than standing on a line, so the stroke is
    // drawn down the shot rather than across it.
    let mut samples: Vec<StrokeSample> = Vec::new();
    for row in 0..6 {
        let y = wide.y0 + wide.height() * (row as f64 / 5.0);
        for i in 0..20 {
            let t = i as f64 / 19.0;
            samples.push(StrokeSample::new(
                Point::new(wide.x0 + wide.width() * t, y),
                1.0,
            ));
        }
    }

    let pieces = effect_artwork(
        kind,
        &EffectStroke {
            samples: &samples,
            size: stage.height() * 0.22,
            color: Color::from_rgb8(0xC8, 0xD4, 0xE6),
            conditioning: Conditioning::smoothing(0.0),
        },
    );
    if pieces.is_empty() {
        return out;
    }

    let layer = scene.add_stage_layer(kind.label(), LayerKind::Normal);
    // In front: weather is between the camera and the shot.
    scene.update_layer(layer, |l| l.depth = -0.8);
    let mut register = |canvas: &buzz_scene::Canvas, brush: &buzz_scene::SoftBrush| {
        let id = scene.next_image_id();
        let name = scene.images().unique_name(kind.label());
        scene.images_mut().insert(canvas.to_asset(id, name, brush))
    };
    for shape in buzz_scene::art::to_shapes(&pieces, &mut register) {
        if scene.add_shape(layer, shape).is_some() {
            out.pieces += 1;
        }
    }
    out.layers.push(layer);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn staged() -> (Scene, f64) {
        let mut scene = Scene::default();
        let stage = scene.stage().stage_rect();
        let horizon = stage.y0 + stage.height() * 0.62;
        // A layer already there, standing in for a cast that has been staged.
        scene.add_stage_layer("Cast", LayerKind::Normal);
        (scene, horizon)
    }

    /// **A scenery puts artwork on the stage**, on layers of its own.
    #[test]
    fn a_forest_lays_trees_and_grass() {
        let (mut scene, horizon) = staged();
        let before = scene.layers().len();
        let out = lay(&mut scene, Scenery::Forest, horizon, None);

        assert_eq!(out.layers.len(), 2, "a treeline and grass");
        assert!(out.pieces > 0, "nothing was drawn");
        assert_eq!(scene.layers().len(), before + 2);
    }

    /// **Bare is bare.** The default has to cost nothing, or every scene that
    /// did not ask for scenery pays for it.
    #[test]
    fn bare_lays_nothing() {
        let (mut scene, horizon) = staged();
        let before = scene.layers().len();
        let out = lay(&mut scene, Scenery::Bare, horizon, None);
        assert!(out.layers.is_empty());
        assert_eq!(out.pieces, 0);
        assert_eq!(scene.layers().len(), before);
    }

    /// **Scenery sits at its own depths**, so the parallax comes for free —
    /// far things behind, near things in front.
    #[test]
    fn scenery_is_arranged_in_depth() {
        let (mut scene, horizon) = staged();
        let out = lay(&mut scene, Scenery::Forest, horizon, None);
        let depths: Vec<f64> = out
            .layers
            .iter()
            .filter_map(|id| scene.layers().get(*id).map(|l| l.depth))
            .collect();
        assert_eq!(depths.len(), 2);
        assert!(
            depths[0] > depths[1],
            "the treeline should be further away than the grass: {depths:?}"
        );
    }

    /// **Every scenery lays something**, so a brief that names one is never
    /// answered with an empty set.
    #[test]
    fn every_scenery_lays_something() {
        for what in [
            Scenery::Forest,
            Scenery::City,
            Scenery::Meadow,
            Scenery::Waterside,
        ] {
            let (mut scene, horizon) = staged();
            let out = lay(&mut scene, what, horizon, None);
            assert!(out.pieces > 0, "{} laid nothing", what.label());
        }
    }

    /// **The prose triggers read what a writer would write.**
    #[test]
    fn a_brief_names_its_own_scenery() {
        assert_eq!(Scenery::from_prose("Night. A dark forest."), Scenery::Forest);
        assert_eq!(Scenery::from_prose("Ana walks down the street."), Scenery::City);
        assert_eq!(Scenery::from_prose("Day. A field of grass."), Scenery::Meadow);
        assert_eq!(Scenery::from_prose("Sunset by the river."), Scenery::Waterside);
        assert_eq!(Scenery::from_prose("Interior. A kitchen."), Scenery::Bare);
    }

    /// **A city with trees in it is a city.** The skyline is what makes it read
    /// as one, so the more specific reading wins.
    #[test]
    fn the_more_specific_scenery_wins() {
        assert_eq!(
            Scenery::from_prose("A city street lined with trees."),
            Scenery::City
        );
    }

    /// **A storm brings rain**, whether the writer said so or not — the same
    /// rule that already brings it cloud, kept in one place.
    #[test]
    fn a_storm_brings_its_own_rain() {
        assert_eq!(weather_for(Setting::Storm), Some(EffectKind::Rain));
        for dry in [
            Setting::Daylight,
            Setting::Sunset,
            Setting::Night,
            Setting::Interior,
        ] {
            assert_eq!(weather_for(dry), None, "{} is not wet", dry.label());
        }
    }

    /// **Weather goes in front of the shot**, because rain falls between the
    /// camera and everything else.
    #[test]
    fn weather_falls_in_front() {
        let (mut scene, _) = staged();
        let out = lay_weather(&mut scene, EffectKind::Rain);
        assert!(out.pieces > 0, "no rain was drawn");
        let depth = scene
            .layers()
            .get(out.layers[0])
            .map(|l| l.depth)
            .unwrap_or(0.0);
        assert!(depth < 0.0, "rain was put behind the shot: {depth}");
    }

    /// **Far scenery goes behind the cast, near scenery in front.**
    ///
    /// The bug the guide's figure caught: every layer was added at the front,
    /// and a comment said they went behind. A forest painted over the actor.
    #[test]
    fn a_treeline_goes_behind_the_cast_and_grass_in_front() {
        let mut scene = Scene::default();
        let stage = scene.stage().stage_rect();
        let horizon = stage.y0 + stage.height() * 0.62;
        // The arrangement a staged set has: sky at the back, cast in front.
        let sky = scene.add_stage_layer("Sky", LayerKind::Normal);
        let cast = scene.add_stage_layer("Cast", LayerKind::Normal);

        let out = lay(&mut scene, Scenery::Forest, horizon, Some(sky));
        let index = |id| scene.stage_layer_index(id).expect("on the stage");

        let (treeline, grass) = (out.layers[0], out.layers[1]);
        // Front first, so a larger index is further back.
        assert!(
            index(treeline) > index(cast),
            "the treeline is painted over the cast"
        );
        assert!(
            index(treeline) < index(sky),
            "the treeline went behind the sky, where nobody can see it"
        );
        assert!(
            index(grass) < index(cast),
            "the grass should be in front of the cast, at their feet"
        );
    }

    /// **The same brief lays the same scenery twice.** Effect strokes are
    /// deterministic, and a set that shuffled itself between runs would make
    /// re-directing a brief reshuffle the whole background.
    #[test]
    fn scenery_is_reproducible() {
        let count = || {
            let (mut scene, horizon) = staged();
            lay(&mut scene, Scenery::City, horizon, None).pieces
        };
        assert_eq!(count(), count());
    }
}
