//! **Filling a staged set** — the treeline, the skyline, the grass, the rain.
//!
//! # The gap this closes
//!
//! [`crate::staging`] builds the *arrangement*: a ground plane, a backdrop, a
//! light rig that agrees with itself, and a cast standing at plausible sizes.
//! What it has never built is anything to look at. After it ran, the largest
//! remaining task in the shot was drawing the background — and the fifteen
//! effect brushes that would paint it had been sitting in
//! [`buzz_scene::effect_brush`] the whole time, reachable only by hand.
//!
//! So this is the join: a setting, and the strokes an animator would have
//! dragged for it.
//!
//! # It lays strokes, it does not invent a brush
//!
//! Every piece of scenery here is **one effect-brush stroke** — the same call
//! the Brush tool makes, with the same budgets and the same determinism. What
//! lands on the layer is ordinary grouped artwork: selectable, movable,
//! deletable, and drawable-over. Nothing here is live and nothing re-runs.
//!
//! That matters more than it sounds. A background generated by some private
//! path would be a background the animator could not extend with the brush
//! that made it; going through the public brush means the treeline they get
//! and the treeline they paint next to it are the same kind of thing.
//!
//! # Depth, and why the strokes are not all on one layer
//!
//! Scenery goes on its own layers at its own depths, behind the cast and in
//! front of the sky. A treeline at the horizon and grass at the camera's feet
//! are different distances, and putting them on one layer would flatten the
//! parallax the depth system already gives for free.

use buzz_geom::{Conditioning, Point, StrokeSample};
use buzz_scene::{
    EffectKind, EffectStroke, LayerKind, Scene, effect_artwork,
};
use peniko::Color;

use crate::staging::Setting;

/// **What is in the shot besides the ground and the sky.**
///
/// A choice rather than something inferred from the setting, because the
/// setting says *when* and this says *where*: a night could be a forest or a
/// street, and the light rig is the same either way.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Scenery {
    /// Nothing. The bare set [`crate::staging::build`] has always made.
    #[default]
    Bare,
    /// A treeline along the horizon and grass in the foreground.
    Forest,
    /// A lit skyline along the horizon, and street lamps on the path.
    City,
    /// **A handful of low houses**, trees behind them, grass in front.
    ///
    /// Not a small city. A city reads as a city because of its *skyline* --
    /// tall, flat-topped, repeated -- and shrinking one gives you a row of
    /// sheds, not a village. What says village is the mixture: roofs at two
    /// heights among trees, warm windows rather than a lit grid, and ground
    /// coming right up to the door.
    Village,
    /// Open ground: grass near, and a thin line of trees far off.
    Meadow,
    /// A shore: water at the horizon, grass on the bank.
    Waterside,
}

impl Scenery {
    pub fn label(self) -> &'static str {
        match self {
            Self::Bare => "Bare",
            Self::Forest => "Forest",
            Self::City => "City",
            Self::Village => "Village",
            Self::Meadow => "Meadow",
            Self::Waterside => "Waterside",
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::Bare => "Ground and sky, and nothing between them",
            Self::Forest => "A treeline along the horizon, grass at the front",
            Self::City => "A lit skyline, and street lamps down the path",
            Self::Village => "Low houses among trees, with the ground up to the door",
            Self::Meadow => "Open ground: grass near, a thin line of trees far off",
            Self::Waterside => "A shore, with the bank in front of it",
        }
    }

    /// **Read a scenery out of a brief.**
    ///
    /// The same shape as the director's `clouds` and `water` triggers, and for
    /// the same reason: a writer who says *forest* has said what the shot looks
    /// like, and asking them to say it twice — once in the prose and once in a
    /// dialog — is the kind of thing that makes a tool feel like paperwork.
    ///
    /// Checked most specific first. A brief that says both *city* and *trees*
    /// is a city with trees in it, and the skyline is the thing that makes it
    /// read as one.
    pub fn from_prose(text: &str) -> Self {
        let lower = text.to_lowercase();
        let has = |words: &[&str]| words.iter().any(|w| lower.contains(w));

        if has(&[
            "village", "hamlet", "cottage", "cottages", "farmstead", "settlement",
        ]) {
            // Checked before the city, because "the village street" is a
            // village and matching *street* first would put a skyline on it.
            Self::Village
        } else if has(&[
            "city", "street", "town", "rooftop", "skyline", "alley", "downtown",
            "pavement", "sidewalk",
        ]) {
            Self::City
        } else if has(&["forest", "wood", "trees", "pine", "grove", "thicket"]) {
            Self::Forest
        } else if has(&[
            "river", "lake", "shore", "beach", "sea", "ocean", "canal", "stream",
        ]) {
            Self::Waterside
        } else if has(&["meadow", "field", "hill", "moor", "grass", "plain"]) {
            Self::Meadow
        } else {
            Self::Bare
        }
    }
}

/// **Which part of a set a piece of artwork stands in for.**
///
/// The effect brushes draw a treeline, a verge and a skyline convincingly and
/// generically, and generic is the point of them: they fill a shot in one
/// stroke. What they cannot be is *your* trees. An animator with a drawn oak
/// wants the oak, and until this existed the only way to get it was to lay the
/// brush strokes and then delete them.
///
/// So every entry in a scenery plan names the part it is playing, and a
/// [`SceneryArt`] can put a library symbol in that part instead.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SceneryPart {
    /// Anything standing along the horizon: pines, leafy trees, a far treeline.
    Trees,
    /// Ground cover at the front of the shot: grass, a verge, a bank.
    Grass,
    /// Dwellings and towers: a skyline, a row of houses.
    Buildings,
    /// Practicals standing on the ground: street lamps, lane lights.
    Lamps,
}

impl SceneryPart {
    pub fn label(self) -> &'static str {
        match self {
            Self::Trees => "Trees",
            Self::Grass => "Grass",
            Self::Buildings => "Buildings",
            Self::Lamps => "Lamps",
        }
    }

    pub const ALL: [SceneryPart; 4] = [
        Self::Trees,
        Self::Grass,
        Self::Buildings,
        Self::Lamps,
    ];
}

/// **Your own drawings, in place of the brushes.**
///
/// A symbol per part. Where one is given, the scenery scatters instances of it
/// along the same line the brush would have painted, at the same size and with
/// the same jitter — so a hand-drawn oak lands in a treeline that reads as a
/// treeline rather than as a row of identical stamps.
///
/// Everything left `None` is drawn by the brush, so this composes: your trees
/// with the generated grass is a perfectly ordinary thing to want.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SceneryArt {
    pub trees: Option<buzz_scene::SymbolId>,
    pub grass: Option<buzz_scene::SymbolId>,
    pub buildings: Option<buzz_scene::SymbolId>,
    pub lamps: Option<buzz_scene::SymbolId>,
}

impl SceneryArt {
    pub fn get(&self, part: SceneryPart) -> Option<buzz_scene::SymbolId> {
        match part {
            SceneryPart::Trees => self.trees,
            SceneryPart::Grass => self.grass,
            SceneryPart::Buildings => self.buildings,
            SceneryPart::Lamps => self.lamps,
        }
    }

    pub fn set(&mut self, part: SceneryPart, symbol: Option<buzz_scene::SymbolId>) {
        match part {
            SceneryPart::Trees => self.trees = symbol,
            SceneryPart::Grass => self.grass = symbol,
            SceneryPart::Buildings => self.buildings = symbol,
            SceneryPart::Lamps => self.lamps = symbol,
        }
    }

    pub fn is_empty(&self) -> bool {
        SceneryPart::ALL.iter().all(|p| self.get(*p).is_none())
    }
}

/// What was laid down.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SceneryReport {
    /// The layers made, back to front.
    pub layers: Vec<buzz_scene::LayerId>,
    /// Objects added across all of them.
    pub pieces: usize,
}

/// **Lay the scenery for `what` into `scene`.**
///
/// `horizon_y` is where the ground meets the sky — [`crate::staging::build`]
/// knows it and this does not, and guessing it from the stage rectangle would
/// put a treeline through the middle of a low-horizon shot.
///
/// # Where the layers land
///
/// `backdrop` is the sky layer, when there is one. Everything **far** — a
/// treeline, a skyline — is moved to sit directly in front of it and therefore
/// behind the cast; everything **near** — grass, a bank — stays at the front,
/// where a foreground belongs.
///
/// Getting this wrong is not subtle. The first version added every layer at the
/// front and said in a comment that they went behind, and the figure it was
/// meant to illustrate came back with a forest painted over the actor.
pub fn lay(
    scene: &mut Scene,
    what: Scenery,
    horizon_y: f64,
    backdrop: Option<buzz_scene::LayerId>,
) -> SceneryReport {
    lay_with(scene, what, horizon_y, backdrop, &SceneryArt::default())
}

/// [`lay`], with your own drawings in whichever parts you have them for.
///
/// See [`SceneryArt`]. An empty one is exactly [`lay`], which is why the two
/// share every line below rather than being two arrangements to keep in step.
pub fn lay_with(
    scene: &mut Scene,
    what: Scenery,
    horizon_y: f64,
    backdrop: Option<buzz_scene::LayerId>,
    art: &SceneryArt,
) -> SceneryReport {
    let mut out = SceneryReport::default();
    if what == Scenery::Bare {
        return out;
    }
    let stage = scene.stage().stage_rect();
    // Wider than the stage, and by the same margin the backdrop uses: a camera
    // following somebody into the wings must not run off the end of the
    // treeline any more than it may run off the end of the sky.
    let x0 = stage.x0 - stage.width();
    let x1 = stage.x1 + stage.width();

    // (name, kind, y, size, colour, depth) — back to front.
    //
    // **The sizes were tuned against the render, not reasoned about.** A brush
    // size is the scale of everything the effect lays down, and the first set
    // of numbers here — picked by eye from the stage height — produced a
    // treeline that filled the frame and dwarfed the cast. The figure in the
    // guide is what showed it; these are what came back.
    // The last field is **far**: does this go behind the cast, or in front?
    let plan: Vec<(&str, EffectKind, SceneryPart, f64, f64, Color, f64, bool)> = match what {
        Scenery::Bare => Vec::new(),
        Scenery::Forest => vec![
            (
                "Treeline",
                EffectKind::PineTrees,
                SceneryPart::Trees,
                horizon_y,
                stage.height() * 0.11,
                Color::from_rgb8(0x1E, 0x2E, 0x24),
                0.7,
                true,
            ),
            (
                "Grass",
                stage_grass(),
                SceneryPart::Grass,
                stage.y1 - stage.height() * 0.04,
                stage.height() * 0.045,
                Color::from_rgb8(0x2C, 0x44, 0x2E),
                -0.3,
                false,
            ),
        ],
        Scenery::City => vec![
            (
                "Skyline",
                EffectKind::Buildings,
                SceneryPart::Buildings,
                horizon_y,
                stage.height() * 0.15,
                Color::from_rgb8(0x18, 0x1C, 0x2A),
                0.8,
                true,
            ),
            (
                "Street Lamps",
                EffectKind::Lamps,
                SceneryPart::Lamps,
                horizon_y + stage.height() * 0.10,
                stage.height() * 0.09,
                Color::from_rgb8(0xFF, 0xD9, 0x9E),
                0.2,
                true,
            ),
        ],
        // **A village is trees, then houses, then the ground they stand on.**
        //
        // The trees go along the horizon first, so the houses are *in* somewhere
        // rather than on a blank field. The houses are their own brush and not
        // the skyline shrunk: that was the first attempt and it came back as a
        // row of small tower blocks, because what makes a skyline read as one is
        // its shape and not its size. The verge is laid last so the grass grows
        // in front of the doors rather than behind them.
        Scenery::Village => vec![
            (
                "Village Trees",
                EffectKind::LeafyTrees,
                SceneryPart::Trees,
                horizon_y - stage.height() * 0.01,
                stage.height() * 0.085,
                Color::from_rgb8(0x2A, 0x3E, 0x2C),
                0.85,
                true,
            ),
            (
                "Houses",
                EffectKind::Houses,
                SceneryPart::Buildings,
                horizon_y + stage.height() * 0.015,
                stage.height() * 0.055,
                Color::from_rgb8(0xB9, 0x9E, 0x7E),
                0.6,
                true,
            ),
            (
                "Verge",
                stage_grass(),
                SceneryPart::Grass,
                stage.y1 - stage.height() * 0.05,
                stage.height() * 0.045,
                Color::from_rgb8(0x35, 0x4E, 0x33),
                -0.3,
                false,
            ),
        ],
        Scenery::Meadow => vec![
            (
                "Far Trees",
                EffectKind::LeafyTrees,
                SceneryPart::Trees,
                horizon_y,
                stage.height() * 0.07,
                Color::from_rgb8(0x33, 0x46, 0x38),
                0.85,
                true,
            ),
            (
                "Grass",
                stage_grass(),
                SceneryPart::Grass,
                stage.y1 - stage.height() * 0.06,
                stage.height() * 0.05,
                Color::from_rgb8(0x3A, 0x54, 0x36),
                -0.3,
                false,
            ),
        ],
        Scenery::Waterside => vec![
            (
                "Far Trees",
                EffectKind::LeafyTrees,
                SceneryPart::Trees,
                horizon_y,
                stage.height() * 0.06,
                Color::from_rgb8(0x2A, 0x3C, 0x33),
                0.85,
                true,
            ),
            (
                "Bank",
                stage_grass(),
                SceneryPart::Grass,
                stage.y1 - stage.height() * 0.05,
                stage.height() * 0.045,
                Color::from_rgb8(0x35, 0x4C, 0x33),
                -0.3,
                false,
            ),
        ],
    };

    for (name, kind, part, y, size, colour, depth, far) in plan {
        // **Your drawing, if you gave one for this part.** Laid on its own
        // layer at the same depth and in the same place in the stack, so
        // everything downstream cannot tell which route the artwork took.
        if let Some(symbol) = art.get(part) {
            let layer = scene.add_stage_layer(name, LayerKind::Normal);
            scene.update_layer(layer, |l| l.depth = depth);
            out.pieces += scatter(scene, layer, symbol, x0, x1, y, size, part);
            place_behind(scene, layer, backdrop, far);
            out.layers.push(layer);
            continue;
        }

        // **A straight stroke across the shot.** The effect brushes scatter
        // along their own spine, so a level line is not a level result — it is
        // a treeline of varying heights standing on level ground, which is what
        // a treeline is.
        let samples: Vec<StrokeSample> = (0..48)
            .map(|i| {
                let t = i as f64 / 47.0;
                StrokeSample::new(Point::new(x0 + (x1 - x0) * t, y), 1.0)
            })
            .collect();

        let pieces = effect_artwork(
            kind,
            &EffectStroke {
                samples: &samples,
                size,
                color: colour,
                // Nothing to smooth: the spine is a straight line already, and
                // conditioning it would only cost time.
                conditioning: Conditioning::smoothing(0.0),
            },
        );
        if pieces.is_empty() {
            continue;
        }

        // Behind everything already staged, and at its own depth so the
        // parallax the depth system gives comes for free.
        let layer = scene.add_stage_layer(name, LayerKind::Normal);
        scene.update_layer(layer, |l| l.depth = depth);

        let mut register = |canvas: &buzz_scene::Canvas, brush: &buzz_scene::SoftBrush| {
            let id = scene.next_image_id();
            let asset_name = scene.images().unique_name(name);
            scene.images_mut().insert(canvas.to_asset(id, asset_name, brush))
        };
        let shapes = buzz_scene::art::to_shapes(&pieces, &mut register);
        for shape in shapes {
            if scene.add_shape(layer, shape).is_some() {
                out.pieces += 1;
            }
        }
        place_behind(scene, layer, backdrop, far);
        out.layers.push(layer);
    }

    // **As long as the shot, not one frame long.**
    //
    // `add_stage_layer` makes a layer a single frame long, and every caller
    // inside `staging::build` is followed by a pass that stretches the lot to
    // the recipe's length. Scenery is laid *after* that pass, so a treeline was
    // drawn on frame 0 and had disappeared by frame 1: an unattended render
    // came back with a forest in the first frame and a bare field for the rest
    // of the shot, which is not the kind of bug you notice in a still.
    let last = scene.frame_count().saturating_sub(1);
    for layer in &out.layers {
        scene.update_stage_layer(*layer, |l| {
            if l.frames.length() <= last {
                l.frames.insert_frame(last);
            }
        });
    }
    out
}

/// **Far scenery goes behind the cast.** Moved to sit directly in front of the
/// backdrop, which is where a horizon belongs; near scenery is left at the
/// front, which is where a foreground belongs.
fn place_behind(
    scene: &mut Scene,
    layer: buzz_scene::LayerId,
    backdrop: Option<buzz_scene::LayerId>,
    far: bool,
) {
    if far
        && let Some(sky) = backdrop
        && let Some(at) = scene.stage_layer_index(sky)
        && at > 0
    {
        // **One less than the sky's index**, because the move takes this layer
        // out of the front first and everything behind it shifts up by one.
        // Reordering to `at` lands it *behind* the sky, where nobody can see
        // it — which is what the first attempt did.
        scene.reorder_stage_layer(layer, at - 1);
    }
}

/// **Stand copies of `symbol` along the line**, the way the brush would have.
///
/// Three things make a row of stamps read as a treeline rather than as
/// wallpaper, and all three are here: the spacing is jittered, the size is
/// jittered, and each copy stands *on* the line rather than being centred on
/// it. Deterministic — seeded from the position — so a scene laid twice is laid
/// the same way, which is the same promise the effect brushes make.
///
/// Returns how many were placed.
fn scatter(
    scene: &mut Scene,
    layer: buzz_scene::LayerId,
    symbol: buzz_scene::SymbolId,
    x0: f64,
    x1: f64,
    y: f64,
    size: f64,
    part: SceneryPart,
) -> usize {
    let Some(bounds) = scene.symbol_bounds(symbol).filter(|b| b.height() > 1e-6) else {
        return 0;
    };

    // How tall a piece stands, as a multiple of the brush size. The brushes
    // themselves work in these proportions — a pine is about twice its size,
    // a blade of grass about one — so a drawing dropped into the same part
    // lands at the same scale as the artwork it is replacing.
    let (tall, spacing, jitter) = match part {
        SceneryPart::Trees => (2.0, 1.05, 0.45),
        SceneryPart::Buildings => (2.2, 1.15, 0.25),
        SceneryPart::Lamps => (1.8, 3.0, 0.15),
        // Grass is a mat rather than a row: pieces overlap, and a gap in it
        // reads as a bald patch.
        SceneryPart::Grass => (1.0, 0.55, 0.20),
    };

    let mut placed = 0usize;
    let mut x = x0;
    let mut i = 0u64;
    // A hard ceiling, because the line is three stages wide and a small drawing
    // would otherwise fill the document with instances.
    while x < x1 && placed < 400 {
        // Deterministic hash of the index: the same line gives the same row.
        let noise = |salt: u64| {
            let mut h = i.wrapping_mul(0x9E37_79B9_7F4A_7C15) ^ salt;
            h ^= h >> 29;
            h = h.wrapping_mul(0xBF58_476D_1CE4_E5B9);
            h ^= h >> 32;
            (h % 10_000) as f64 / 10_000.0
        };

        let vary = 1.0 + (noise(0xA1) - 0.5) * 2.0 * jitter;
        let height = size * tall * vary;
        let scale = height / bounds.height();
        let width = bounds.width() * scale;

        // Its feet on the line: the symbol's own bottom edge goes to `y`.
        let at = buzz_geom::Affine::translate((x - bounds.x0 * scale, y - bounds.y1 * scale))
            * buzz_geom::Affine::scale(scale);
        if scene.add_instance_at(layer, 0, symbol, at).is_some() {
            placed += 1;
        }

        let gap = width * spacing * (1.0 + (noise(0xB2) - 0.5) * 2.0 * jitter);
        x += gap.max(size * 0.1);
        i += 1;
    }
    placed
}

/// Grass, named apart so the two places that want it cannot disagree about
/// which effect grass is.
fn stage_grass() -> EffectKind {
    EffectKind::Grass
}

/// **What weather this setting brings**, if any.
///
/// A storm arrives with rain whether the writer mentioned it or not, for the
/// same reason it arrives with cloud: it is what a storm *is*, and a rule that
/// lived in each caller is a rule that gets out of step.
pub fn weather_for(setting: Setting) -> Option<EffectKind> {
    match setting {
        Setting::Storm => Some(EffectKind::Rain),
        _ => None,
    }
}

/// Lay `weather` across the whole frame, in front of the scenery and behind
/// nothing — rain falls between the camera and everything else.
pub fn lay_weather(scene: &mut Scene, kind: EffectKind) -> SceneryReport {
    let mut out = SceneryReport::default();
    let stage = scene.stage().stage_rect();
    let wide = stage.inflate(stage.width(), stage.height());

    // Weather fills the frame rather than standing on a line, so the stroke is
    // drawn down the shot rather than across it.
    let mut samples: Vec<StrokeSample> = Vec::new();
    for row in 0..6 {
        let y = wide.y0 + wide.height() * (row as f64 / 5.0);
        for i in 0..20 {
            let t = i as f64 / 19.0;
            samples.push(StrokeSample::new(
                Point::new(wide.x0 + wide.width() * t, y),
                1.0,
            ));
        }
    }

    let pieces = effect_artwork(
        kind,
        &EffectStroke {
            samples: &samples,
            size: stage.height() * 0.22,
            color: Color::from_rgb8(0xC8, 0xD4, 0xE6),
            conditioning: Conditioning::smoothing(0.0),
        },
    );
    if pieces.is_empty() {
        return out;
    }

    let layer = scene.add_stage_layer(kind.label(), LayerKind::Normal);
    // In front: weather is between the camera and the shot.
    scene.update_layer(layer, |l| l.depth = -0.8);
    let mut register = |canvas: &buzz_scene::Canvas, brush: &buzz_scene::SoftBrush| {
        let id = scene.next_image_id();
        let name = scene.images().unique_name(kind.label());
        scene.images_mut().insert(canvas.to_asset(id, name, brush))
    };
    for shape in buzz_scene::art::to_shapes(&pieces, &mut register) {
        if scene.add_shape(layer, shape).is_some() {
            out.pieces += 1;
        }
    }
    out.layers.push(layer);
    // As long as the shot, for the same reason as [`lay`] above: a rainstorm
    // that stops after one frame is not weather.
    let last = scene.frame_count().saturating_sub(1);
    scene.update_stage_layer(layer, |l| {
        if l.frames.length() <= last {
            l.frames.insert_frame(last);
        }
    });
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn staged() -> (Scene, f64) {
        let mut scene = Scene::default();
        let stage = scene.stage().stage_rect();
        let horizon = stage.y0 + stage.height() * 0.62;
        // A layer already there, standing in for a cast that has been staged.
        scene.add_stage_layer("Cast", LayerKind::Normal);
        (scene, horizon)
    }

    /// **A scenery puts artwork on the stage**, on layers of its own.
    #[test]
    fn a_forest_lays_trees_and_grass() {
        let (mut scene, horizon) = staged();
        let before = scene.layers().len();
        let out = lay(&mut scene, Scenery::Forest, horizon, None);

        assert_eq!(out.layers.len(), 2, "a treeline and grass");
        assert!(out.pieces > 0, "nothing was drawn");
        assert_eq!(scene.layers().len(), before + 2);
    }

    /// **Bare is bare.** The default has to cost nothing, or every scene that
    /// did not ask for scenery pays for it.
    #[test]
    fn bare_lays_nothing() {
        let (mut scene, horizon) = staged();
        let before = scene.layers().len();
        let out = lay(&mut scene, Scenery::Bare, horizon, None);
        assert!(out.layers.is_empty());
        assert_eq!(out.pieces, 0);
        assert_eq!(scene.layers().len(), before);
    }

    /// **Scenery sits at its own depths**, so the parallax comes for free —
    /// far things behind, near things in front.
    #[test]
    fn scenery_is_arranged_in_depth() {
        let (mut scene, horizon) = staged();
        let out = lay(&mut scene, Scenery::Forest, horizon, None);
        let depths: Vec<f64> = out
            .layers
            .iter()
            .filter_map(|id| scene.layers().get(*id).map(|l| l.depth))
            .collect();
        assert_eq!(depths.len(), 2);
        assert!(
            depths[0] > depths[1],
            "the treeline should be further away than the grass: {depths:?}"
        );
    }

    /// **Every scenery lays something**, so a brief that names one is never
    /// answered with an empty set.
    #[test]
    fn every_scenery_lays_something() {
        for what in [
            Scenery::Forest,
            Scenery::City,
            Scenery::Meadow,
            Scenery::Waterside,
        ] {
            let (mut scene, horizon) = staged();
            let out = lay(&mut scene, what, horizon, None);
            assert!(out.pieces > 0, "{} laid nothing", what.label());
        }
    }

    /// **The prose triggers read what a writer would write.**
    #[test]
    fn a_brief_names_its_own_scenery() {
        assert_eq!(Scenery::from_prose("Night. A dark forest."), Scenery::Forest);
        assert_eq!(Scenery::from_prose("Ana walks down the street."), Scenery::City);
        assert_eq!(Scenery::from_prose("Day. A field of grass."), Scenery::Meadow);
        assert_eq!(Scenery::from_prose("Sunset by the river."), Scenery::Waterside);
        assert_eq!(Scenery::from_prose("Interior. A kitchen."), Scenery::Bare);
    }

    /// **A city with trees in it is a city.** The skyline is what makes it read
    /// as one, so the more specific reading wins.
    #[test]
    fn the_more_specific_scenery_wins() {
        assert_eq!(
            Scenery::from_prose("A city street lined with trees."),
            Scenery::City
        );
    }

    /// **A storm brings rain**, whether the writer said so or not — the same
    /// rule that already brings it cloud, kept in one place.
    #[test]
    fn a_storm_brings_its_own_rain() {
        assert_eq!(weather_for(Setting::Storm), Some(EffectKind::Rain));
        for dry in [
            Setting::Daylight,
            Setting::Sunset,
            Setting::Night,
            Setting::Interior,
        ] {
            assert_eq!(weather_for(dry), None, "{} is not wet", dry.label());
        }
    }

    /// **Weather goes in front of the shot**, because rain falls between the
    /// camera and everything else.
    #[test]
    fn weather_falls_in_front() {
        let (mut scene, _) = staged();
        let out = lay_weather(&mut scene, EffectKind::Rain);
        assert!(out.pieces > 0, "no rain was drawn");
        let depth = scene
            .layers()
            .get(out.layers[0])
            .map(|l| l.depth)
            .unwrap_or(0.0);
        assert!(depth < 0.0, "rain was put behind the shot: {depth}");
    }

    /// **Far scenery goes behind the cast, near scenery in front.**
    ///
    /// The bug the guide's figure caught: every layer was added at the front,
    /// and a comment said they went behind. A forest painted over the actor.
    #[test]
    fn a_treeline_goes_behind_the_cast_and_grass_in_front() {
        let mut scene = Scene::default();
        let stage = scene.stage().stage_rect();
        let horizon = stage.y0 + stage.height() * 0.62;
        // The arrangement a staged set has: sky at the back, cast in front.
        let sky = scene.add_stage_layer("Sky", LayerKind::Normal);
        let cast = scene.add_stage_layer("Cast", LayerKind::Normal);

        let out = lay(&mut scene, Scenery::Forest, horizon, Some(sky));
        let index = |id| scene.stage_layer_index(id).expect("on the stage");

        let (treeline, grass) = (out.layers[0], out.layers[1]);
        // Front first, so a larger index is further back.
        assert!(
            index(treeline) > index(cast),
            "the treeline is painted over the cast"
        );
        assert!(
            index(treeline) < index(sky),
            "the treeline went behind the sky, where nobody can see it"
        );
        assert!(
            index(grass) < index(cast),
            "the grass should be in front of the cast, at their feet"
        );
    }

    /// **The same brief lays the same scenery twice.** Effect strokes are
    /// deterministic, and a set that shuffled itself between runs would make
    /// re-directing a brief reshuffle the whole background.
    #[test]
    fn scenery_is_reproducible() {
        let count = || {
            let (mut scene, horizon) = staged();
            lay(&mut scene, Scenery::City, horizon, None).pieces
        };
        assert_eq!(count(), count());
    }
}
